<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Service\ProGpsApiService;
use App\Jobs\ProcessReportJob;
use App\Models\Report;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

class ReportController extends Controller
{
    public function __construct(protected ProGpsApiService $apiService) {}

    // Get employees for the panel
    public function getEmployees(Request $request)
    {
        $departments = collect($this->apiService->getDepartments()['list'])->keyBy('id');
        $employees = collect($this->apiService->getEmployees()['list']);

        $groupedEmployees = $employees->groupBy(function ($employee) use ($departments) {
            return $departments[$employee['department_id']]['label'] ?? 'Sin Departamento';
        })->sortByDesc(function ($employees) {
            return count($employees);
        })->map(function ($employees, $name) use ($departments) {
            $firstEmployee = $employees->first();
            $departmentId = $firstEmployee['department_id'] ?? null;
            $color = 'cacaca';
            return [
                'id' => $departmentId,
                'name' => $name,
                'color' => $color,
                'employees' => array_values($employees->map(function ($employee) {
                    return [
                        'id' => $employee['id'],
                        'full_name' => $employee['first_name'] . " " . $employee['middle_name'] . " " . $employee['last_name'],
                    ];
                })->toArray()),
            ];
        })->values()->toArray();

        return response()->json($groupedEmployees);
    }

    // Get grouped trackers for the panel
    public function getGroupedTrackers(Request $request)
    {
        $trackers = collect($this->apiService->getTrackers()['list'])->keyBy('id');
        $groups = collect($this->apiService->getGroups()['list'])->keyBy('id');

        $groupedTrackers = $trackers->groupBy(function ($tracker) use ($groups) {
            return $groups[$tracker['group_id']]['title'] ?? 'Grupo Principal';
        })->sortByDesc(function ($trackers) {
            return count($trackers);
        })->map(function ($trackers, $name) use ($groups) {
            $firstTracker = $trackers->first();
            $groupId = $firstTracker['group_id'] ?? null;
            $color = $groups[$groupId]['color'] ?? 'cacaca';
            return [
                'id' => $groupId,
                'name' => $name,
                'color' => $color,
                'trackers' => array_values($trackers->toArray()),
            ];
        })->values()->toArray();

        return response()->json($groupedTrackers);
    }

    // Get list of reports generated by the user
    public function getListOfUsersGeneratedReports(Request $request)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $reports = Report::where('user_id', $userId)->orderBy('created_at', 'desc')->get();

        return response()->json($reports);
    }

    // Process the result of a report | Private Endpoint
    public function processResult(Request $request, $id)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $secret = $request->input('secret');
        $reportData = $request->input('data');

        // if ($secret !== $this->apiService->getSecretKey()) {
        //     return response()->json(['message' => 'Invalid secret key.'], 403);
        // }
        if ($secret !== "xd") {
            return response()->json(['message' => 'Invalid secret key.'], 403);
        }

        if (!$reportData || !is_array($reportData)) {
            return response()->json(['message' => 'Invalid report data.'], 400);
        }

        $report = Report::where('id', $id)->where('user_id', $userId)->first();
        if (!$report) return response()->json(['message' => 'Report not found.'], 404);

        // Update report with the result

        $jsonDir = storage_path('app/reports');
        $jsonPath = $jsonDir . "/report_{$id}.json";
        file_put_contents($jsonPath, json_encode($reportData, JSON_PRETTY_PRINT));

        $report->percent = 100; // Assuming the report is completed
        $report->file_path = $jsonPath;
        $report->save();
    }

    // Get status of report for polling
    public function getStatusOfReport($id)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $report = Report::where('id', $id)->where('user_id', $userId)->first();
        if (!$report) return response()->json(['message' => 'Report not found.'], 404);

        return response()->json([
            'id' => $report->id,
            'percent' => $report->percent,
            'status' => $report->percent < 100 ? 'processing' : 'completed',
        ]);
    }

    // Update report status | Private Endpoint
    public function updateReportStatus(Request $request, $id)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $report = Report::where('id', $id)->where('user_id', $userId)->first();
        if (!$report) return response()->json(['message' => 'Report not found.'], 404);

        $percent = $request->input('percent');
        if (!is_numeric($percent)) {
            return response()->json(['message' => 'Invalid percent value.'], 400);
        }

        $report->percent = (int)$percent;
        $report->save();

        return response()->json(['message' => 'Report status updated successfully.', 'report' => $report]);
    }

    // Retrieve report data
    public function retrieveReport($id)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $report = Report::where('id', $id)->where('user_id', $userId)->first();
        if (!$report) return response()->json(['message' => 'Report not found.'], 404);

        if ($report->percent < 100) {
            return response()->json(['message' => 'Report is still being processed. Please check back later.', 'percent' => $report->percent], 202);
        }

        if ($report->file_path && file_exists($report->file_path)) {
            return response()->json(json_decode(file_get_contents($report->file_path), true));
        }

        return response()->json(['message' => 'Report file not available. Something happened during the creation or storing process.'], 404);
    }

    // Delete report
    public function deleteReport($id)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $report = Report::where('id', $id)->where('user_id', $userId)->first();
        if (!$report) return response()->json(['message' => 'Report not found.'], 404);

        if ($report->file_path && file_exists($report->file_path)) {
            unlink($report->file_path);
        }

        $report->delete();

        return response()->json(['message' => 'Report deleted successfully.']);
    }

    // Generate report
    public function generateReport(Request $request)
    {
        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $reportTypeId = $request->input('report_type_id') ?? 0;
        if (!in_array($reportTypeId, $this->apiService->validReportTypeIds)) return response()->json(['message' => 'Invalid report type id.'], 400);

        $isValidReport = $this->validateReportPayload($request->input('report_payload'), $reportTypeId);
        if (!$isValidReport) return response()->json(['message' => 'Invalid report payload.'], 400);

        $payload = [
            'user_id' => $userId,
            'title' => $request->input('report_payload')['title'],
            'report_type_id' => $reportTypeId,
            'report_payload' => $request->input('report_payload'),
            'percent' => 0,
            'file_path' => null,
        ];

        $report = Report::create($payload);
        if (!$report) return response()->json(['message' => 'Failed to create report.'], 500);

        ProcessReportJob::dispatch($report, $this->apiService->apiKey);

        return response()->json([
            'message' => 'Report is being created. You can check the status later.',
            'report' => $report->toArray(),
        ], 201);
    }

    // Download Report on format XLS
    public function downloadReport(Request $request, $id)
    {
        $format = $request->query('format');
        if (!in_array($format, ['xlsx', 'pdf'])) return response()->json(['message' => 'Invalid format specified.'], 400);

        $userId = $this->apiService->getUserInfo()['user_info']['id'] ?? null;
        if (!$userId) return response()->json(['message' => 'User id of the hash provided doesnt exist on the platform.'], 401);

        $report = Report::where('id', $id)->where('user_id', $userId)->first();
        if (!$report) return response()->json(['message' => 'Report not found.'], 404);

        if ($report->percent === -1) {
            return response()->json(['message' => 'Something happened with the report', 'percent' => $report->percent], 500);
        } else if ($report->percent < 100) {
            return response()->json(['message' => 'Report is still being processed. Please check back later.', 'percent' => $report->percent], 202);
        }

        if ($report->file_path && file_exists($report->file_path)) {
            if ($format === 'xlsx') {
                return $this->exportGenericReportToExcel(json_decode(file_get_contents($report->file_path), true));
            }
        }

        return response()->json(['message' => 'Report file not available. Something happened during the creation or storing process.'], 404);
    }

    // Export report data to Excel
    public function exportGenericReportToExcel(array $reportData)
    {
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $numberOfColumns = count($reportData['columns_dimensions_for_excel_file'] ?? []);

        // ------------------- HEADER -------------------
        $lastLetter = Coordinate::stringFromColumnIndex(max(1, $numberOfColumns));

        $sheet->mergeCells('A1:' . $lastLetter . '1');
        $sheet->setCellValue('A1', $reportData['title'] ?? 'Reporte General');
        $sheet->setCellValue('A2', $reportData['date']);

        $sheet->getStyle('A1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 16],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_BOTTOM],
        ]);

        $sheet->mergeCells('A2:' . $lastLetter . '2');
        $sheet->getStyle('A2')->applyFromArray([
            'font' => ['bold' => true, 'size' => 12],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_TOP],
        ]);
        // ------------------------------------------------

        // ------------------- SUMMARY ---------------------
        $summary = $reportData['summary'] ?? null;
        $row = 3;
        if ($summary) {
            $sheet->mergeCells("A{$row}:B{$row}");
            $sheet->setCellValue("A{$row}", $summary['title'] ?? 'Resumen');

            $sheet->getStyle("A{$row}")->applyFromArray([
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => ltrim($summary['color'] ?? 'eeece1', '#')]],
                'font' => ['bold' => true],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ]);

            $row++;
            foreach ($summary['rows'] ?? [] as $summaryRow) {
                $sheet->setCellValue("A{$row}", $summaryRow['title']);
                $sheet->setCellValue("B{$row}", $summaryRow['value']);
                $sheet->getStyle("A{$row}")->applyFromArray([
                    'font' => ['bold' => true],
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => ltrim($summary['color'] ?? 'eeece1', '#')]],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT],
                ]);
                $sheet->getStyle("B{$row}")->applyFromArray([
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT],
                ]);
                $row++;
            }

            $sheet->getStyle("A3:B" . ($row - 1))->applyFromArray([
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                        'color' => ['rgb' => '000000']
                    ]
                ]
            ]);
        }

        $row += 1;

        // ------------------- DATA ---------------------
        $writeGroup = function ($group, &$row, $sheet, $depth = 0) use (&$writeGroup, $lastLetter) {
            $columns = $group['content']['columns'] ?? [];

            $sheet->setCellValue("A{$row}", $group['groupLabel']);
            $sheet->mergeCells("A{$row}:{$lastLetter}{$row}");

            $sheet->getStyle("A{$row}:{$lastLetter}{$row}")->applyFromArray([
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => ltrim($group['bgColor'] ?? 'eeece1', '#')]
                ],
                'font' => ['bold' => true],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                        'color' => ['rgb' => '000000']
                    ]
                ],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]
            ]);
            $row++;

            if (isset($group['content']) && isset($group['content']['rows']) && isset($group['content']['columns'])) {
                $content = $group['content'];
                $columns = $content['columns'] ?? [];

                $colNames = array_map(fn($col) => $col['name'], $columns);
                $sheet->fromArray($colNames, null, "A{$row}");

                $sheet->getStyle("A{$row}:{$lastLetter}{$row}")->applyFromArray([
                    'font' => ['bold' => true],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => ['rgb' => ltrim($content['bgColor'] ?? 'EBF1DE', '#')]
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                            'color' => ['rgb' => '000000']
                        ]
                    ],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]
                ]);
                $row++;

                foreach ($content['rows'] as $dataRow) {
                    $sheet->fromArray(array_map(fn($col) => $dataRow[$col['key']], $columns), null, "A{$row}");
                    $sheet->getStyle("A{$row}:{$lastLetter}{$row}")->applyFromArray([
                        'borders' => [
                            'allBorders' => [
                                'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                                'color' => ['rgb' => '000000']
                            ]
                        ],
                        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT]
                    ]);
                    $row++;
                }

                $sheet->mergeCells("A{$row}:{$lastLetter}{$row}");
                $row++;
            } elseif (isset($group['content'])) {
                foreach ($group['content'] ?? [] as $childGroup) {
                    $writeGroup($childGroup, $row, $sheet, $depth + 1);
                }
            }
        };

        foreach ($reportData['data'] ?? [] as $group) {
            $writeGroup($group, $row, $sheet);
        }

        // ------------------ Final styling -------------------
        $sheet->getRowDimension(1)->setRowHeight(28.2);
        $sheet->getRowDimension(2)->setRowHeight(27.6);

        $columnsDimensions = $reportData['columns_dimensions_for_excel_file'] ?? null;
        if ($columnsDimensions) {
            foreach ($columnsDimensions as $col => $width) {
                $sheet->getColumnDimension($col)->setWidth($width);
            }
        }

        $filename = 'Reporte.xlsx';
        $tempFile = tempnam(sys_get_temp_dir(), $filename);
        (new Xlsx($spreadsheet))->save($tempFile);

        return response()->download($tempFile, $filename)->deleteFileAfterSend(true);
    }

    // VALIDATION METHODS FOR REPORTS PAYLOADS
    public function validateReportPayload(array $payload,  $reportTypeId)
    {
        switch ($reportTypeId) {
            case 1:
                return $this->validateOdometerReportPayload($payload);
            case 2:
                return $this->validateSpeedupReportPayload($payload);
            case 3:
                return $this->validateNotificationsReportPayload($payload);
            case 4:
                return $this->validateVehicleInsurancePoliceExpirationReportPayload($payload);
            case 5:
                return $this->validateDriverLicenseExpirationReportPayload($payload);
            default:
                return false;
        }
    }

    public function validateDriverLicenseExpirationReportPayload(array $payload)
    {
        $hasFromDate = (isset($payload['from']) && $this->isValidIso8601($payload['from'])) || $payload['from'] == null;
        $hasToDate = (isset($payload['to']) && $this->isValidIso8601($payload['to'])) || $payload['to'] == null;
        $hasTrackers = isset($payload['employees']) && is_array($payload['employees']) && count($payload['employees']) > 0;
        $hasTitle = isset($payload['title']) && !empty($payload['title']);

        return $hasFromDate && $hasToDate && $hasTrackers && $hasTitle;
    }

    public function validateVehicleInsurancePoliceExpirationReportPayload(array $payload)
    {
        $hasFromDate = (isset($payload['from']) && $this->isValidIso8601($payload['from'])) || $payload['from'] == null;
        $hasToDate = (isset($payload['to']) && $this->isValidIso8601($payload['to'])) || $payload['to'] == null;
        $hasTrackers = isset($payload['trackers']) && is_array($payload['trackers']) && count($payload['trackers']) > 0;
        $hasTitle = isset($payload['title']) && !empty($payload['title']);

        return $hasFromDate && $hasToDate && $hasTrackers && $hasTitle;
    }

    public function validateNotificationsReportPayload(array $payload)
    {
        $hasFromDate = isset($payload['from']) && $this->isValidIso8601($payload['from']);
        $hasToDate = isset($payload['to']) && $this->isValidIso8601($payload['to']);
        $hasTitle = isset($payload['title']) && !empty($payload['title']);
        $hasTrackers = (isset($payload['trackers']) && is_array($payload['trackers']) && count($payload['trackers']) > 0) || $payload['trackers'] == "all";
        $hasNotificationsFilter = (isset($payload['notifications']) && is_array($payload['notifications']) && count($payload['notifications']) > 0) || $payload['notifications'] == "all";
        $hasGroups = (isset($payload['groups']) && is_array($payload['groups']) && count($payload['groups']) > 0) || $payload['groups'] == "all";

        return $hasFromDate && $hasToDate && $hasTrackers && $hasTitle && $hasNotificationsFilter && $hasGroups;
    }

    public function validateOdometerReportPayload(array $payload)
    {
        $hasDate = isset($payload['date']) && $this->isValidIso8601($payload['date']);
        $hasTrackers = isset($payload['trackers']) && is_array($payload['trackers']) && count($payload['trackers']) > 0;
        $hasTitle = isset($payload['title']) && !empty($payload['title']);

        return $hasDate && $hasTrackers && $hasTitle;
    }

    public function validateSpeedupReportPayload(array $payload)
    {
        $hasFromDate = isset($payload['from']) && $this->isValidIso8601($payload['from']);
        $hasToDate = isset($payload['to']) && $this->isValidIso8601($payload['to']);
        $min_duration = isset($payload['min_duration']) && is_numeric($payload['min_duration']) && $payload['min_duration'] >= 0;
        $allowedSpeed = isset($payload['allowed_speed']) && is_numeric($payload['allowed_speed']) && $payload['allowed_speed'] > 0;
        $hasTrackers = isset($payload['trackers']) && is_array($payload['trackers']) && count($payload['trackers']) > 0;
        $hasTitle = isset($payload['title']) && !empty($payload['title']);

        return $hasToDate && $hasFromDate && $hasTrackers && $hasTitle && $min_duration && $allowedSpeed;
    }

    protected function isValidIso8601($date)
    {
        try {
            return \Carbon\Carbon::parse($date) !== false;
        } catch (\Exception $e) {
            return false;
        }
    }
}
